ASide:
  - Room: "pcj"
    Holes:
      - Side: Right
        Idx: 0
        Kind: out
        ReqOut:
          Dashes: zero
          Difficulty: perfect
      - Side: Left
        Idx: 0
        Kind: in
      - Side: Up
        Idx: 0
        Kind: none
  - Room: "sideflipShrine"
    Worth: 0.1
    Flags:
      - ScugHelper-AllowSideflipping:set
    Holes:
      - Side: Left
        Idx: 0
        Kind: inout
      - Side: Right
        Idx: 0
        Kind: inout
      - Side: Up
        Idx: 0
        Kind: none
